### ISSUE TITLE
Renew letsencrypt SSL certificate 

### ISSUE THREAD

**Issue by BeZazz** [Prajithp/letsencrypt-cpanel#8]
Just playing and I noticed.

While it lists the provider of an expired Cert as 
COMODO CA Limited

Clicking Renew letsencrypt SSL certificate 
Offers to renew the domain of the expired Comodo cetificate.

I am assuming this is a bug?

**Comment by Prajithp** [comment]
Can you please check this now, as I have updated the code. Please test it and let me know.

**Comment by BeZazz** [comment]
The Comodo expired domain still show up as a renewal option.
Click Renew returns.
"Could not find the domain config file, please revoke the ssl cert and install it again"

IMO the domain should not show up under "renew" only "install".

**Comment by Prajithp** [comment]
yes, I will work on it when I get much free time. Also, I don't have any servers with active cpanel license.

**Comment by Erreu** [comment]
I have a license that I am not currently using at the moment. Would that help you with this?

**Comment by ashworthconsulting** [comment]
@Prajithp You can get a developer license here:

http://cpanel.com/developer-license-app/

Separately, I'll get you a VPS to use to develop/test with. Just let me know the desired specs (RAM, CPU, disk, etc). I believe you still have my contact info as well.

**Comment by Prajithp** [comment]
@Erreu @ashworthconsulting Thanks for the offer. Not needed now as I  bought new server :)
@BeZazz Could you please upgrade to the latest release?

**Comment by BeZazz** [comment]
The Comodo expired domain no longer shows up under renew :)
It also no longer shows up under install :( , while you should not be offered to renew an expired third party cert you should still have the option to install on the domain.
